import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, posix } from "node:path";
import { finding, parseFrontmatter, proseLines, text } from "./docs.mjs";
import { listFiles, reader } from "./git.mjs";

const SKILLS = ".claude/skills/";
const RULES = ".claude/rules/";
const OWNED_FILES = [".cursor/mcp.json", ".codex/config.toml", ".kiro/settings/mcp.json"];
const OWNED_DIRS = [".agents/skills/", ".kiro/skills/", ".cursor/rules/", ".kiro/steering/"];
const KEYS = ["type", "command", "args", "env", "url", "headers"];
const REF = /\$\{([A-Za-z_]\w*)\}/g;
const CAP = 200;
const MAX_HOPS = 5;

export const isOwned = (p) => OWNED_FILES.includes(p) || OWNED_DIRS.some((d) => p.startsWith(d));
const note = (src) => `Generated by project-standard from ${src}. Edit the source, then run project-standard sync.`;
const hasRef = (v) => typeof v === "string" && v.includes("${");
const mapValues = (obj, fn) => obj && Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, fn(v)]));
const compact = (obj) => Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));
const lineCount = (src) => (src === "" ? 0 : src.replace(/\n$/, "").split("\n").length);
const norm = (b) => (Buffer.isBuffer(b) ? b.toString("latin1") : Buffer.from(b).toString("latin1")).replace(/\r\n/g, "\n");

export function expandBraces(glob) {
  const m = glob.match(/\{([^{}]*)\}/);
  if (!m) return [glob];
  return m[1].split(",").flatMap((alt) => expandBraces(glob.slice(0, m.index) + alt + glob.slice(m.index + m[0].length)));
}

const tomlKey = (k) => (/^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k));
const tomlValue = (v) =>
  Array.isArray(v) ? `[${v.map((x) => JSON.stringify(x)).join(", ")}]`
  : typeof v === "object" ? `{ ${Object.entries(v).map(([k, x]) => `${tomlKey(k)} = ${JSON.stringify(x)}`).join(", ")} }`
  : JSON.stringify(v);

function codexServer(name, s, fail) {
  const table = {};
  if (s.url !== undefined) {
    if (hasRef(s.url)) return fail("Codex cannot expand ${VAR} in url");
    table.url = s.url;
    const plain = {};
    const fromEnv = {};
    for (const [h, v] of Object.entries(s.headers ?? {})) {
      const bearer = h.toLowerCase() === "authorization" && v.match(/^Bearer \$\{(\w+)\}$/);
      const whole = v.match(/^\$\{(\w+)\}$/);
      if (bearer) table.bearer_token_env_var = bearer[1];
      else if (whole) fromEnv[h] = whole[1];
      else if (hasRef(v)) return fail(`Codex cannot expand \${VAR} inside header ${h}`);
      else plain[h] = v;
    }
    if (Object.keys(plain).length) table.http_headers = plain;
    if (Object.keys(fromEnv).length) table.env_http_headers = fromEnv;
  } else {
    if (hasRef(s.command) || (s.args ?? []).some(hasRef)) return fail("Codex cannot expand ${VAR} in command or args");
    table.command = s.command;
    if (s.args?.length) table.args = s.args;
    const literal = {};
    const forward = [];
    for (const [k, v] of Object.entries(s.env ?? {})) {
      if (v === `\${${k}}`) forward.push(k);
      else if (hasRef(v)) return fail(`Codex forwards env by name only: set ${k} to \${${k}}`);
      else literal[k] = v;
    }
    if (forward.length) table.env_vars = forward;
    if (Object.keys(literal).length) table.env = literal;
  }
  return [`[mcp_servers.${tomlKey(name)}]`, ...Object.entries(table).map(([k, v]) => `${k} = ${tomlValue(v)}`)].join("\n");
}

function renderMcp(src, out, errors) {
  let json;
  try {
    json = JSON.parse(src);
  } catch (e) {
    return errors.push({ path: ".mcp.json", message: `not valid JSON: ${e.message}` });
  }
  const cursor = {};
  const kiro = {};
  const codex = [];
  for (const [name, s] of Object.entries(json.mcpServers ?? {})) {
    const fail = (message) => void errors.push({ path: ".mcp.json", message: `server ${name}: ${message}` });
    const extra = Object.keys(s).filter((k) => !KEYS.includes(k));
    if (extra.length) { fail(`keys ${extra.join(", ")} are not portable`); continue; }
    if (s.type === "sse") { fail("SSE is not portable; Codex speaks stdio and streamable HTTP only"); continue; }
    if (/\$\{[^}]*:-/.test(JSON.stringify(s))) { fail("${VAR:-default} is not portable"); continue; }
    const toCursor = (v) => (typeof v === "string" ? v.replace(REF, "${env:$1}") : v);
    if (s.url !== undefined) {
      cursor[name] = compact({ url: toCursor(s.url), headers: mapValues(s.headers, toCursor) });
      if (hasRef(s.url)) { fail("Kiro expands ${VAR} only in env and headers"); continue; }
      kiro[name] = compact({ url: s.url, headers: s.headers });
    } else {
      cursor[name] = compact({ type: "stdio", command: toCursor(s.command), args: s.args?.map(toCursor), env: mapValues(s.env, toCursor) });
      if (hasRef(s.command) || (s.args ?? []).some(hasRef)) { fail("Kiro expands ${VAR} only in env and headers"); continue; }
      kiro[name] = compact({ command: s.command, args: s.args, env: s.env });
    }
    const block = codexServer(name, s, fail);
    if (block) codex.push(block);
  }
  out.set(".cursor/mcp.json", `${JSON.stringify({ mcpServers: cursor }, null, 2)}\n`);
  out.set(".kiro/settings/mcp.json", `${JSON.stringify({ mcpServers: kiro }, null, 2)}\n`);
  out.set(".codex/config.toml", [`# ${note(".mcp.json")}`, ...codex].join("\n\n") + "\n");
}

function renderRule(path, src, out, errors, flats) {
  const flat = path.slice(RULES.length).replace(/\.md$/, "").replaceAll("/", "-");
  if (flats.has(flat)) return errors.push({ path, message: `generates the same file name as ${flats.get(flat)}; rename one` });
  flats.set(flat, path);
  const fm = parseFrontmatter(src);
  const body = fm ? src.split("\n").slice(fm.end + 1).join("\n") : src;
  const paths = fm?.data.paths;
  const globs = paths == null ? null : [paths].flat().flatMap(expandBraces);
  const description = fm?.data.description;
  const marker = `<!-- ${note(path)} -->\n`;
  const cursor = [description && `description: ${description}`, globs ? `globs: ${globs.join(",")}` : null, `alwaysApply: ${!globs}`].filter(Boolean);
  const kiro = globs ? ["inclusion: fileMatch", `fileMatchPattern: ${JSON.stringify(globs)}`] : ["inclusion: always"];
  out.set(`.cursor/rules/${flat}.mdc`, `---\n${cursor.join("\n")}\n---\n${marker}${body}`);
  out.set(`.kiro/steering/${flat}.md`, `---\n${kiro.join("\n")}\n---\n${marker}${body}`);
}

export function render(files, read) {
  const out = new Map();
  const errors = [];
  const flats = new Map();
  for (const p of files) {
    if (p === ".mcp.json") renderMcp(text(read(p)) ?? "{}", out, errors);
    else if (p.startsWith(SKILLS)) {
      const rest = p.slice(SKILLS.length);
      const buf = read(p);
      out.set(`.agents/skills/${rest}`, buf);
      out.set(`.kiro/skills/${rest}`, buf);
    } else if (p.startsWith(RULES) && p.endsWith(".md")) renderRule(p, text(read(p)), out, errors, flats);
  }
  return { out, errors };
}

export function checkDrift(files, read) {
  const { out, errors } = render(files, read);
  const findings = errors.map((e) => finding(e.path, 1, "drift", e.message));
  for (const [p, content] of out) {
    const actual = read(p);
    if (actual === null) findings.push(finding(p, 1, "drift", "missing: run project-standard sync and stage the result"));
    else if (norm(actual) !== norm(content)) findings.push(finding(p, 1, "drift", "differs from its source: run project-standard sync (never edit a generated copy)"));
  }
  for (const p of files) if (isOwned(p) && !out.has(p)) findings.push(finding(p, 1, "drift", "has no source: run project-standard sync to remove it"));
  return findings;
}

export function sync(root) {
  const files = listFiles(root, { untracked: true }).filter((p) => existsSync(join(root, p)));
  const read = reader(root, false);
  const { out, errors } = render(files, read);
  if (errors.length) return { errors, written: [], removed: [] };
  const written = [];
  const removed = [];
  for (const [p, content] of out) {
    const current = read(p);
    if (current !== null && norm(current) === norm(content)) continue;
    mkdirSync(dirname(join(root, p)), { recursive: true });
    writeFileSync(join(root, p), content);
    written.push(p);
  }
  for (const p of files) {
    if (!isOwned(p) || out.has(p)) continue;
    rmSync(join(root, p));
    removed.push(p);
  }
  return { errors, written, removed };
}

export function checkAgentsCap(files, read) {
  const agents = text(read("AGENTS.md"));
  if (agents === null) return [];
  const tracked = new Set(files);
  const seen = new Set();
  const parts = [];
  let total = 0;
  const visit = (path, src, hops) => {
    seen.add(path);
    const n = lineCount(src);
    total += n;
    parts.push(`${path} ${n}`);
    if (hops >= MAX_HOPS) return;
    for (const { text: prose } of proseLines(src)) {
      for (const m of prose.matchAll(/(?:^|\s)@([^\s`'"()<>[\]]+)/g)) {
        const target = m[1].replace(/[.,;:!?]+$/, "");
        if (target.startsWith("~") || target.startsWith("/")) continue;
        const p = posix.normalize(posix.join(posix.dirname(path), target));
        if (tracked.has(p) && !seen.has(p)) visit(p, text(read(p)) ?? "", hops + 1);
      }
    }
  };
  visit("AGENTS.md", agents, 0);
  for (const p of files) {
    if (!p.startsWith(RULES) || !p.endsWith(".md") || seen.has(p)) continue;
    const src = text(read(p)) ?? "";
    if (parseFrontmatter(src)?.data.paths != null) continue;
    const n = lineCount(src);
    total += n;
    parts.push(`${p} ${n}`);
  }
  if (total < CAP) return [];
  return [finding("AGENTS.md", 1, "agents", `${total} lines with imports and path-less rules; keep it under ${CAP} (${parts.join(", ")})`)];
}
