#!/usr/bin/env node
/**
 * Wires Codex and Cursor on this machine to the fleet. Claude Code gets the
 * fleet from the plugin; the other two read plain directories, so this links
 * or generates what they read from the same sources the plugin ships.
 *
 *   skills        ~/.agents/skills/<name>       link to skills/<category>/<name>   (Codex, Cursor)
 *   agents        ~/.codex/agents/<name>.toml   generated from agents/<name>.md
 *                 ~/.cursor/agents/<name>.md    generated from agents/<name>.md
 *   instructions  ~/.codex/AGENTS.md            generated from claude/CLAUDE.md
 *   MCP servers   ~/.codex/config.toml          managed block
 *                 ~/.cursor/mcp.json            merged by server name
 *   hooks         ~/.codex/hooks.json           guard-dangerous-bash and inject-mode merged in
 *                 ~/.cursor/hooks.json          guard-dangerous-bash and inject-mode merged in
 *
 *     node scripts/link-agents.mjs             apply
 *     node scripts/link-agents.mjs --dry-run   print the plan, change nothing
 *
 * Idempotent. It never replaces what it did not create: agent files and
 * AGENTS.md without its marker, skill folders or links that point outside this
 * repo, MCP servers already defined by the user. A config file it edits is
 * rewritten with LF line endings and copied to `<name>.bak-<date>` before its
 * first change of the day. Every JSON input is parsed before the first write.
 * Install the plugin in Claude Code, and in Codex either the plugin or this
 * script: both together list every skill twice.
 */
import {
  copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync,
  readlinkSync, realpathSync, rmdirSync, symlinkSync, unlinkSync, writeFileSync,
} from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const HOME = process.env.LINK_AGENTS_HOME ?? homedir();
const WIN = platform() === "win32";
const DRY = process.argv.includes("--dry-run");
const MARK = "generated by jgabriel-skills scripts/link-agents.mjs";
const GUARD = "guard-dangerous-bash.mjs";
const MODE_HOOK = "inject-mode.mjs";
const MODES = [["caveman", "ultra"], ["ponytail", "ultra"], ["i-have-adhd"]];
const BLOCK_TAG = "jgabriel-skills";
const SETTINGS_ENV = ["OLLAMA_MODE", "OLLAMA_URL", "EMBEDDING_MODEL", "EMBEDDING_DIMENSIONS", "QDRANT_MODE", "QDRANT_URL"];

const slash = (p) => p.replace(/\\/g, "/");
const quote = (p) => (/\s/.test(p) ? `"${p}"` : p);
const readText = (p) => readFileSync(p, "utf8").replace(/^﻿/, "").replace(/\r\n/g, "\n");
const readJson = (p) => (existsSync(p) ? JSON.parse(readText(p)) : null);
const stamp = () => new Date().toISOString().slice(0, 10).replace(/-/g, "");

export function parseAgent(text) {
  const m = text.replace(/\r\n/g, "\n").match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  const field = (key) => m[1].match(new RegExp(`^${key}:\\s*(.+)$`, "m"))?.[1].trim();
  return { name: field("name"), description: field("description"), tools: field("tools") ?? "", body: m[2].trim() };
}

const readOnly = (agent) => !/\b(Edit|Write)\b/.test(agent.tools);

export function toCodexAgent(agent) {
  if (agent.body.includes("'''")) throw new Error(`${agent.name}: body contains ''' and cannot be a TOML literal string`);
  return [
    `# ${MARK} from agents/${agent.name}.md`,
    `name = ${JSON.stringify(agent.name)}`,
    `description = ${JSON.stringify(agent.description)}`,
    ...(readOnly(agent) ? ['sandbox_mode = "read-only"'] : []),
    `developer_instructions = '''`,
    agent.body,
    `'''`,
    "",
  ].join("\n");
}

export function toCursorAgent(agent) {
  return [
    "---",
    `name: ${agent.name}`,
    `description: ${JSON.stringify(agent.description)}`,
    ...(readOnly(agent) ? ["readonly: true"] : []),
    "---",
    `<!-- ${MARK} from agents/${agent.name}.md -->`,
    "",
    agent.body,
    "",
  ].join("\n");
}

export function setBlock(text, tag, body, where) {
  const open = `# >>> ${tag} >>>`;
  const close = `# <<< ${tag} <<<`;
  const escaped = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const rest = text.replace(new RegExp(`${escaped(open)}[\\s\\S]*?${escaped(close)}\\n?`), "");
  if (body == null) return rest.replace(/^\n+/, "");
  const block = `${open}\n${body}\n${close}\n`;
  if (!rest.trim()) return block;
  return where === "top" ? `${block}\n${rest.replace(/^\n+/, "")}` : `${rest.replace(/\n+$/, "")}\n\n${block}`;
}

export function rescueForeignTables(text, tag, names) {
  const inside = text.match(new RegExp(`# >>> ${tag} >>>\\n([\\s\\S]*?)# <<< ${tag} <<<`))?.[1] ?? "";
  const ours = new RegExp(`^\\[mcp_servers\\.(${names.join("|")})[.\\]]`);
  const foreign = inside.split(/^(?=\[)/m).filter((t) => t.startsWith("[") && !ours.test(t)).map((t) => t.trim());
  if (!foreign.length) return text;
  return `${setBlock(text, tag, null).replace(/\n+$/, "")}\n\n${foreign.join("\n\n")}\n`;
}

export function renderCodexMcp(servers) {
  return Object.entries(servers)
    .map(([name, s]) =>
      [
        `[mcp_servers.${name}]`,
        `command = ${JSON.stringify(s.command)}`,
        `args = ${JSON.stringify(s.args)}`,
        ...(s.env ? ["", `[mcp_servers.${name}.env]`, ...Object.entries(s.env).map(([k, v]) => `${k} = ${JSON.stringify(v)}`)] : []),
      ].join("\n"),
    )
    .join("\n\n");
}

function upsertHook(list, entry, marker) {
  const owned = (h) => h.command?.includes(marker) || h.hooks?.some((x) => x.command?.includes(marker));
  const at = list.findIndex(owned);
  const kept = list.filter((h) => !owned(h));
  if (entry) kept.splice(at === -1 ? kept.length : at, 0, entry);
  list.splice(0, list.length, ...kept);
}

export function mergeCodexHook(config, command) {
  const entry = { matcher: "Bash", hooks: [{ type: "command", command, timeout: 10, statusMessage: "Checking Bash command" }] };
  upsertHook(((config.hooks ??= {}).PreToolUse ??= []), entry, GUARD);
  return config;
}

export function mergeCursorHook(config, command) {
  config.version ??= 1;
  upsertHook(((config.hooks ??= {}).preToolUse ??= []), { command, matcher: "Shell", timeout: 10 }, GUARD);
  return config;
}

export function mergeCodexMode(config, command) {
  const entry = command && { matcher: "startup|resume|clear|compact", hooks: [{ type: "command", command, timeout: 5, statusMessage: "Loading modes" }] };
  upsertHook(((config.hooks ??= {}).SessionStart ??= []), entry, MODE_HOOK);
  return config;
}

export function mergeCursorMode(config, command) {
  config.version ??= 1;
  upsertHook(((config.hooks ??= {}).sessionStart ??= []), command && { command, timeout: 5 }, MODE_HOOK);
  return config;
}

export function mcpServers(agent, settingsEnv = {}) {
  const local = join(HOME, ".local", "bin", WIN ? "serena.exe" : "serena");
  const npx = WIN ? "npx.cmd" : "npx";
  const servers = {
    serena: {
      command: existsSync(local) ? slash(local) : "serena",
      args: ["start-mcp-server", "--context", agent === "codex" ? "codex" : "ide", "--project", ".", "--enable-web-dashboard", "false", "--open-web-dashboard", "false"],
      env: { PYTHONUTF8: "1" },
    },
    playwright: { command: npx, args: ["-y", "@playwright/mcp@latest"] },
  };
  if (SETTINGS_ENV.every((k) => settingsEnv[k] !== undefined)) {
    servers.socraticode = { command: npx, args: ["-y", "socraticode"], env: Object.fromEntries(SETTINGS_ENV.map((k) => [k, String(settingsEnv[k])])) };
  }
  return servers;
}

const done = [];
function say(step, state, detail) {
  console.log(`  ${{ ok: "+", skip: "=", warn: "!" }[state]} ${step}${detail ? ` — ${detail}` : ""}`);
  done.push(state);
}

function put(path, content, { backup = false } = {}) {
  const current = existsSync(path) ? readText(path) : null;
  if (current === content) return false;
  if (DRY) return true;
  mkdirSync(dirname(path), { recursive: true });
  if (backup && current !== null && !existsSync(`${path}.bak-${stamp()}`)) copyFileSync(path, `${path}.bak-${stamp()}`);
  writeFileSync(path, content);
  return true;
}

function putOwned(path, content) {
  if (existsSync(path) && !readText(path).includes(MARK)) return "foreign";
  return put(path, content) ? "changed" : "same";
}

function linkSkills() {
  const dest = join(HOME, ".agents", "skills");
  const wanted = new Map();
  for (const category of readdirSync(join(REPO, "skills"))) {
    for (const name of readdirSync(join(REPO, "skills", category))) {
      const dir = join(REPO, "skills", category, name);
      if (existsSync(join(dir, "SKILL.md"))) wanted.set(name, dir);
    }
  }
  if (!DRY) mkdirSync(dest, { recursive: true });
  const entries = existsSync(dest) ? readdirSync(dest) : [];
  let linked = 0;
  const blocked = [];
  const norm = (p) => {
    const s = p.replace(/^\\\\\?\\/, "").replace(/[\\/]+$/, "");
    return WIN ? s.toLowerCase() : s;
  };
  const roots = [join(REPO, "skills"), realpathSync(join(REPO, "skills"))].map((p) => norm(p) + sep);
  const owned = (path) => {
    const target = norm(resolve(dirname(path), readlinkSync(path)));
    return roots.some((root) => target.startsWith(root));
  };
  for (const name of entries) {
    const path = join(dest, name);
    if (lstatSync(path).isSymbolicLink() && owned(path) && !wanted.has(name)) {
      if (!DRY) unlinkSafe(path);
      say(`unlinked ${name}`, "ok", "no longer in skills/");
    }
  }
  for (const [name, src] of wanted) {
    const path = join(dest, name);
    if (existsSync(path) || entries.includes(name)) {
      const link = lstatSync(path).isSymbolicLink();
      let same = false;
      try {
        same = link && realpathSync(path) === realpathSync(src);
      } catch {}
      if (same) continue;
      if (!link || !owned(path)) {
        blocked.push(name);
        continue;
      }
      if (!DRY) unlinkSafe(path);
    }
    if (!DRY) symlinkSync(src, path, WIN ? "junction" : "dir");
    linked++;
  }
  say(`skills linked into ${slash(dest)}`, linked ? "ok" : "skip", `${wanted.size - blocked.length} present, ${linked} new`);
  if (blocked.length) say("skills left alone", "warn", `${blocked.join(", ")} exist there as real folders or links to elsewhere`);
}

function unlinkSafe(path) {
  try {
    unlinkSync(path);
  } catch {
    rmdirSync(path);
  }
}

function pruneGenerated(dir, ext, keep) {
  if (!existsSync(dir)) return;
  for (const file of readdirSync(dir)) {
    const path = join(dir, file);
    if (file.endsWith(ext) && !keep.has(file) && readText(path).includes(MARK)) {
      if (!DRY) unlinkSync(path);
      say(`removed ${file}`, "ok", "source agent is gone");
    }
  }
}

function linkAgents(codexHome, cursorHome) {
  const agents = readdirSync(join(REPO, "agents"))
    .filter((f) => f.endsWith(".md"))
    .map((f) => parseAgent(readText(join(REPO, "agents", f))));
  for (const [home, ext, render, label] of [
    [codexHome, ".toml", toCodexAgent, "Codex"],
    [cursorHome, ".md", toCursorAgent, "Cursor"],
  ]) {
    if (!existsSync(home)) {
      say(`${label} agents`, "skip", `${slash(home)} not found`);
      continue;
    }
    const dir = join(home, "agents");
    const results = agents.map((a) => putOwned(join(dir, a.name + ext), render(a)));
    pruneGenerated(dir, ext, new Set(agents.map((a) => a.name + ext)));
    const foreign = agents.filter((_, i) => results[i] === "foreign").map((a) => a.name);
    say(`${label} agents`, results.includes("changed") ? "ok" : "skip", `${results.filter((r) => r !== "foreign").length}/${agents.length} in sync`);
    if (foreign.length) say(`${label} agents left alone`, "warn", `${foreign.join(", ")} exist and were not generated here`);
  }
}

function linkCodexConfig(codexHome, settingsEnv) {
  if (!existsSync(codexHome)) return say("Codex config", "skip", `${slash(codexHome)} not found`);
  const instructions = putOwned(join(codexHome, "AGENTS.md"), `<!-- ${MARK} from claude/CLAUDE.md -->\n${readText(join(REPO, "claude", "CLAUDE.md"))}`);
  say("Codex AGENTS.md", instructions === "foreign" ? "warn" : instructions === "changed" ? "ok" : "skip", instructions === "foreign" ? "a hand-written one exists, left alone" : "from claude/CLAUDE.md");

  const path = join(codexHome, "config.toml");
  let text = existsSync(path) ? readText(path) : "";
  const outside = text.replace(new RegExp(`# >>> ${BLOCK_TAG}-(\\w+) >>>[\\s\\S]*?# <<< ${BLOCK_TAG}-\\1 <<<\\n?`, "g"), "");
  const root = outside.split(/^\[/m)[0];
  const top = /^project_doc_max_bytes\s*=/m.test(root) ? null : "project_doc_max_bytes = 65536";
  const servers = Object.fromEntries(Object.entries(mcpServers("codex", settingsEnv)).filter(([n]) => !new RegExp(`^\\[mcp_servers\\.${n}[.\\]]`, "m").test(outside)));
  text = rescueForeignTables(text, `${BLOCK_TAG}-mcp`, ["serena", "playwright", "socraticode"]);
  const withMcp = setBlock(text, `${BLOCK_TAG}-mcp`, renderCodexMcp(servers), "bottom");
  text = setBlock(withMcp, `${BLOCK_TAG}-top`, top, "top");
  say("Codex config.toml", put(path, text, { backup: true }) ? "ok" : "skip", `MCP: ${Object.keys(servers).join(", ")}${top ? "; project_doc_max_bytes" : ""}`);
}

function linkJson(path, label, current, update) {
  if (!existsSync(dirname(path))) return say(label, "skip", `${slash(dirname(path))} not found`);
  const next = update(current ?? {});
  say(label, put(path, `${JSON.stringify(next, null, 2)}\n`, { backup: true }) ? "ok" : "skip");
}

function main() {
  const codexHome = process.env.CODEX_HOME || join(HOME, ".codex");
  const cursorHome = join(HOME, ".cursor");
  const paths = {
    settings: join(HOME, ".claude", "settings.json"),
    cursorMcp: join(cursorHome, "mcp.json"),
    codexHooks: join(codexHome, "hooks.json"),
    cursorHooks: join(cursorHome, "hooks.json"),
  };
  const json = {};
  for (const [key, path] of Object.entries(paths)) {
    try {
      json[key] = readJson(path);
    } catch (e) {
      console.error(`cannot parse ${slash(path)}: ${e.message}\nnothing was changed`);
      process.exit(1);
    }
  }
  const settingsEnv = json.settings?.env ?? {};
  const node = quote(WIN ? "node" : process.execPath);
  const guard = `${node} ${quote(slash(join(REPO, "hooks", GUARD)))}`;
  const modeCommand = (flag = "") => `${node} ${quote(slash(join(REPO, "hooks", MODE_HOOK)))} ${flag}${MODES.map(([skill, level]) => (level ? `${skill}:${level}` : skill)).join(" ")}`;

  console.log(`${DRY ? "plan (dry run)" : "apply"}: ${slash(REPO)} -> ${slash(HOME)}`);
  linkSkills();
  linkAgents(codexHome, cursorHome);
  linkCodexConfig(codexHome, settingsEnv);
  linkJson(paths.cursorMcp, "Cursor mcp.json", json.cursorMcp, (config) => {
    config.mcpServers ??= {};
    const kept = [];
    for (const [name, s] of Object.entries(mcpServers("cursor", settingsEnv))) {
      const ours = { type: "stdio", ...s };
      if (!(name in config.mcpServers)) config.mcpServers[name] = ours;
      else if (JSON.stringify(config.mcpServers[name]) !== JSON.stringify(ours)) kept.push(name);
    }
    if (kept.length) say("Cursor MCP servers left alone", "warn", `${kept.join(", ")} already defined there`);
    return config;
  });
  linkJson(paths.codexHooks, "Codex hooks.json", json.codexHooks, (config) => mergeCodexMode(mergeCodexHook(config, guard), modeCommand()));
  linkJson(paths.cursorHooks, "Cursor hooks.json", json.cursorHooks, (config) => mergeCursorMode(mergeCursorHook(config, guard), modeCommand("--cursor ")));
  console.log("\nNext: in Codex run /hooks and trust the new guard hook; restart Codex and Cursor to pick up skills and MCP.");
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
